Task_6:Question_1: Arrays

You are given a space separated list of numbers.

Your task is to print a reversed NumPy array with the element type float.

In [1]:
import numpy

def arrays(arr):
    return numpy.array(arr[::-1],float)
arr = input().strip().split(' ')
result = arrays(arr)
print(result)

1 2 3 4 5 6 7 8 9 10
[10.  9.  8.  7.  6.  5.  4.  3.  2.  1.]


Task_6:Question_2: Shape and Reshape

You are given a space separated list of nine integers. Your task is to convert this list into a 3X3 NumPy array.

In [2]:
import numpy as np
arr=np.array(list(map(int,input().split(" "))))
print(arr.reshape(3,3))

1 2 3 4 5 6 7 8 9
[[1 2 3]
 [4 5 6]
 [7 8 9]]


Task_6:Question_3: Transpose and Flatten

U are given a NXM integer array matrix with space separated elements (N = rows and M = columns).

Your task is to print the transpose and flatten results.

In [3]:
import numpy as np
n,m=list(map(int,input().split()))
l=[]
for i in range(n):
    l.append(list(map(int,input().split())))
arr=np.array(l)
print(arr.transpose())
print(arr.flatten())

2 2
1 2
3 4
[[1 3]
 [2 4]]
[1 2 3 4]


Task_6:Question_4: Concatenate

You are given two integer arrays of size NXP and PXM ( N&M are rows, and P is the column). 

Your task is to concatenate the arrays along axis 0.

In [4]:
import numpy as np
n,m,p=list(map(int,input().split(" ")))
l=[]
k=[]
for i in range(n):
    l.append(list(map(int,input().split(" "))))
for i in range(m):
    k.append(list(map(int,input().split(" "))))
arr1=np.array(l)
arr2=np.array(k)
print(np.concatenate((arr1,arr2),axis=0))

4 3 2
1 2
1 2
1 2
3 4
3 4
3 4
3 4
[[1 2]
 [1 2]
 [1 2]
 [3 4]
 [3 4]
 [3 4]
 [3 4]]


Task_6:Question_5 : Zeros and Ones

You are given the shape of the array in the form of space-separated integers, each integer representing the size of different dimensions, your task is to print an array of the given shape and integer type using the tools numpy.zeros and numpy.one

In [5]:
import numpy as np
l=tuple(map(int,input().split(" ")))
print(np.zeros(l,dtype=np.int))
print(np.ones(l,dtype=np.int))

3 3
[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]


Task_6:Question_6: Eye and Identity

our task is to print an array of size NXM with its main diagonal elements as 1's and 0's everywhere else.

In [6]:
import numpy as np
np.set_printoptions(legacy='1.13')
n,m=list(map(int,input().split(" ")))
print(np.eye(n,m,k=0))

3 3
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


Task_6:Question_7: Array Mathematics

You are given two integer arrays, A and B of dimensions NXM.
Your task is to perform the following operations:

Add (A+B)

Subtract (A-B)

Multiply (A*B)

Integer Division (A/B)

Mod (A%B)

Power (A** B)

In [7]:
import numpy as np
n,m=list(map(int,input().split(" ")))
l1=[]
l2=[]
for i in range(n):
    l1.append(list(map(int,input().split(" "))))
for i in range(n):
    l2.append(list(map(int,input().split(" "))))
A=np.array(l1)
B=np.array(l2)
print(A+B)
print(A-B)
print(A*B)
print(A//B)
print(A%B)
print(A**B)

1 4
1 2 3 4
5 6 7 8
[[ 6  8 10 12]]
[[-4 -4 -4 -4]]
[[ 5 12 21 32]]
[[0 0 0 0]]
[[1 2 3 4]]
[[    1    64  2187 65536]]


Task_6:Question_8: Floor, Ceil and Rint

 Given a 1-D array, A. Your task is to print the Floor, Ceil and Rint of all the elements of A. 

In [8]:
import numpy as np
np.set_printoptions(legacy='1.13')
A=np.array(list(map(float,input().split())))
print(np.floor(A))
print(np.ceil(A))
print(np.rint(A))

1.1 2.2 3.3 4.4 5.5 6.6 7.7 8.8 9.9
[ 1.  2.  3.  4.  5.  6.  7.  8.  9.]
[  2.   3.   4.   5.   6.   7.   8.   9.  10.]
[  1.   2.   3.   4.   6.   7.   8.   9.  10.]


Task_6:Question_9: Sum and Prod

ou are given a 2-D array with dimensions NXM.

Your task is to perform the sum tool over axis 0 and then find the product of that result.

In [9]:
import numpy as np
n,m=list(map(int,input().split(" ")))
l=[]
for i in range(n):
    l.append(list(map(int,input().split(" "))))
arr=np.array(l)
sum0=np.sum(arr,axis=0)
print(np.prod(sum0))

2 2
1 2
3 4
24


Task_6:Question_10: Min and Max

You are given a 2-D array with dimensions NXM.

Your task is to perform the min function over axis 1 and then find the max of that.

In [10]:
import numpy as np
n,m=list(map(int,input().split(" ")))
l=[]
for i in range(n):
    l.append(list(map(int,input().split(" "))))
arr=np.array(l)
print(np.max(np.min(arr,axis=1)))

4 2
2 5
3 7
1 3
4 0
3


Task_6:Question_11: Mean, Var, and Std

You are given a 2-D array of size NXM.

Your task is to find:

The mean along axis 1

The var along axis 0

The std along axis None

In [11]:
import numpy
n,m=list(map(int,input().split(" ")))
arr=numpy.array([input().split() for i in range(n)],int)
print(numpy.mean(arr,axis=1))
print(numpy.var(arr,axis=0))
print(numpy.std(arr,None))

2 2
1 2
3 4
[ 1.5  3.5]
[ 1.  1.]
1.11803398875


Task_6:Question_12: Dot and Cross

You are given two arrays A and B. Both have dimensions of NXN.

Your task is to compute their matrix product.

In [12]:
import numpy
n=int(input())
arr1=numpy.array([input().split() for i in range(n)],int)
arr2=numpy.array([input().split() for i in range(n)],int)
print(numpy.dot(arr1,arr2))

2
1 2
3 4
1 2
3 4
[[ 7 10]
 [15 22]]


Task_6:Question_13: Inner and Outer

You are given two arrays: A and B.

Your task is to compute their inner and outer product.

In [13]:
import numpy
arr1=numpy.array(input().split(),int)
arr2=numpy.array(input().split(),int)
print(numpy.inner(arr1,arr2))
print(numpy.outer(arr1,arr2))

0 1
2 3
3
[[0 0]
 [2 3]]


Task_6:Question_14: Polynomials

You are given the coefficients of a polynomial P.

Your task is to find the value of P at point X.

In [14]:
import numpy
l=list(map(float,input().split()))
x=float(input())
print(numpy.polyval(l,x))

1.1 2 3
0
3.0


Task_6:Question_15 : Linear Algebra

You are given a square matrix A with dimensions NXN. Your task is to find the determinant. 

In [15]:
import numpy
n=int(input())
arr=numpy.array([input().split() for i in range(n)],float)
print(numpy.linalg.det(arr))

2
1.1 1.1
1.1 1.1
0.0
